### ISSUE TITLE
probably a dumb question

### ISSUE THREAD

**Issue by develperbayman** [Parking-Master/FPS2#5]
how do i launch my own server instance? i was hoping to run on my orange pi 5 ....i mean is it nodejs or do i just drop the files in my www folder? (i dont know how to use node really)

**Comment by Parking-Master** [comment]
Hello there. During development I used my own server instance to test the game. You can clone this repository using the `clone` command, go into that directory/folder, and run `node server.js`.

**Comment by develperbayman** [comment]
cool thank you

**Comment by NarmakTwo** [comment]
I took a look through the server.js code and it looks like it could be run fully static. So would hosting it through something like `python3 -m http.server 8080` work?
