### ISSUE TITLE
Running fully statically

### ISSUE THREAD

**Issue by NarmakTwo** [Parking-Master/FPS2#6]
I took a look through the server.js code and it looks like it could be run fully static. So would hosting it through something like `python3 -m http.server 8080` work?

**Comment by Parking-Master** [comment]
Hello @NarmakTwo! Yes, all of the game's files are hosted open-source on this GitHub repository. Everything can be run locally by doing a simple `node server.js` and going to http://localhost:8080 in your browser.

Or you can use any method such as the command you posted. Anything will work to host the files statically.

**Comment by NarmakTwo** [comment]
is there any way to host the backend too?

**Comment by Parking-Master** [comment]
There actually is no backend. The only service that uses backend is PubNub and Back4App's Parse. These are in the cloud though, and used as an API in the client-side code for FPS2. However, you could get your own API keys from PubNub and Back4App it you'd like to clone your own standalone game that doesn't use the public database/multiplayer APIs.
